apiVersion: v1
kind: PersistentVolume
metadata:
  name: yash-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/yash_PV_dir"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yash-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual